string device_name
string build_date
string serial_number
uint32 device_revision

uint32    number_of_pcbs
uint32[] pcb_serial_numbers
string[] pcb_names

string imager_name
uint32 imager_type
uint32 imager_width
uint32 imager_height

string lens_name
uint32 lens_type
float32 nominal_baseline
float32 nominal_focal_length
float32 nominal_relative_aperture

uint32 lighting_type
uint32 number_of_lights

string laser_name
uint32 laser_type

string motor_name
uint32 motor_type
float32 motor_gear_reduction

string api_build_date
uint16 api_version
string firmware_build_date
uint16 firmware_version

uint64 bitstream_version
uint64 bitstream_magic
uint64 fpga_dna
