name: Build MultiSense ROS 2

on:
  push:
    branches:
      - master
  release:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}-${{ matrix.ros_distro }}-build
      cancel-in-progress: ${{ github.ref_name != 'master' }}
    strategy:
      fail-fast: false
      matrix:
        ros_distro:
          - jazzy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ros-${{ matrix.ros_distro }}-image_transport \
            ros-${{ matrix.ros_distro }}-generate-parameter-library \
            nlohmann-json3-dev
          sudo rm -rf /var/lib/apt/lists/*
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            ros_codename=${{ matrix.ros_distro }}
