name: Build MultiSense ROS 2

on:
  push:
    branches:
      - master
  release:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}-${{ matrix.ros_distro }}-build
      cancel-in-progress: ${{ github.ref_name != 'master' }}
    strategy:
      fail-fast: false
      matrix:
        ros_distro:
          - jazzy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - name: Install rosdep
        run: |
          set -eux
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-rosdep
          sudo rosdep init || true
          rosdep update
      - name: Install dependencies with rosdep
        run: |
          set -eux
          ls -la
          rosdep install \
            --from-paths . \
            --ignore-src \
            --rosdistro ${{ matrix.ros_distro }} \
            -y -r
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            ros_codename=${{ matrix.ros_distro }}
